name: Deploy to EKS

on:
  workflow_dispatch

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # -------- ECR --------
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image variables
        id: vars
        run: |
          IMAGE_TAG="latest"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          FULL_IMAGE="${{ steps.login-ecr.outputs.registry }}/${{secrets.ECR_REPOSITORY }}:$IMAGE_TAG"
          echo "FULL_IMAGE=$FULL_IMAGE" >> $GITHUB_ENV
  

      - name: Build Docker image
        run: |
          docker build -t $FULL_IMAGE .

      - name: Push Docker image
        run: |
          docker push $FULL_IMAGE

    # -------- EKS --------
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Replace image in Deployment YAML
        run: |
          sed -i "s|REPLACE_IMAGE|$FULL_IMAGE|g" k8s/deployment.yml
          

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml || true
          
